[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 300
