[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT && php artisan migrate:fresh && php artisan db:seed && php artisan storage:link"
healthcheckPath = "/up"
healthcheckTimeout = 60
