[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 60
